# Nipy : Neuroimaging in Python

# Nipy (Community)

* http://nipy.org/ Or http://nipy.github.io    

## Projects

* http://nipy.org/project-directory/
* Overview
    - File I/O and data management
        - Nibabel
            - Read / write access to some common neuroimaging file formats.
            - http://nipy.org/nibabel/
        - Scitran SDM
            - SciTran SDM delivers efficient and robust archiving, organization, and sharing of scientific data.
            - https://github.com/scitran/sdm
    - Functional MRI
        - Nilearn
            - Nilearn is a Python module for fast and easy statistical learning on NeuroImaging data.
            - http://nilearn.github.io/
        - Nipy
            - NIPY is not only the name of the Neuroimaging in Python community, but also a python project for analysis of structural and functional neuroimaging data.
            - http://nipy.org/nipy/
        - Nitime
            - Nitime is a library for time-series analysis of data from neuroscience experiments.
            - http://nipy.org/nitime/
        - PyMVPA
            - PyMVPA is a Python package intended to ease statistical learning analyses of large datasets.
            - http://www.pymvpa.org/
    - Diffusion MRI
        - Dipy 
            - Dipy is a free and open source software project focusing mainly on diffusion magnetic resonance imaging (dMRI) analysis.
            - http://nipy.org/dipy/
    - Human electrophysiology
        - MNE
            - MNE is a software package for processing magnetoencephalography (MEG) and electroencephalography (EEG) data.
            - http://www.martinos.org/mne/stable/index.html
    - Analysis pipeline management 
        - Nipype
            - Nipype, an open-source, community-developed initiative under the umbrella of NiPy, is a Python project that provides a uniform interface to existing neuroimaging software and facilitates interaction between these packages within a single workflow.
            - http://nipy.org/nipype/

# PyMVPA

* Inatallation
* Dataset basics and concepts
* Getting data in shape

## Inatallation

* http://www.pymvpa.org/installation.html

* MacOS X 환경
    - git clone git://github.com/PyMVPA/PyMVPA.git
    - brew install libsvm
    - brew install https://raw.github.com/cobrateam/formulae/master/swig.rb
    - cd PyMVPA
    - source ~/.venv/neuropy/bin/acitvate
    - A) 
        - python setup.py install --with-libsvm
        - cp -r mvpa2 ~/.venv/neuropy/lib/python2.7/site-packages
    - B)
        - make 3rd
        - python setup.py install

In [1]:
import mvpa2

## Dataset basics and concepts

* basic 
* Load fMRI data

#### basic

In [2]:
from mvpa2.tutorial_suite import *

In [3]:
data = [[  1,  1, -1],
           [  2,  0,  0],
           [  3,  1,  1],
           [  4,  0, -1]]

In [4]:
ds = Dataset(data)

In [5]:
ds

Dataset(array([[ 1,  1, -1],
       [ 2,  0,  0],
       [ 3,  1,  1],
       [ 4,  0, -1]]), sa=SampleAttributesCollection(items=[]), fa=FeatureAttributesCollection(items=[]), a=DatasetAttributesCollection(items=[]))

In [6]:
dir(ds)

['C',
 'O',
 'S',
 'T',
 'UC',
 'UT',
 '__array__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__len__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__repr_full__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_append_mapper',
 '_collection_id2obj',
 'a',
 'aggregate_features',
 'append',
 'chunks',
 'coarsen_chunks',
 'copy',
 'fa',
 'find_collection',
 'from_channeltimeseries',
 'from_hdf5',
 'from_wizard',
 'get_attr',
 'get_mapped',
 'get_nsamples_per_attr',
 'get_samples_by_attr',
 'get_samples_per_chunk_target',
 'idhash',
 'init_origids',
 'item',
 'mapper',
 'nfeatures',
 'nsamples',
 'random_samples',
 'remove_invariant_features',
 'remove_nonfinite_features',
 'sa',
 'samples',
 'save',
 'select',
 'set_attr',
 'shape',
 'summary',
 'summary_targets',
 'targets',
 'uniquechunks',
 'uniquet

In [7]:
ds.shape

(4, 3)

In [8]:
len(ds)

4

In [9]:
ds.nfeatures

3

In [10]:
ds.samples

array([[ 1,  1, -1],
       [ 2,  0,  0],
       [ 3,  1,  1],
       [ 4,  0, -1]])

In [11]:
one_d = [ 0, 1, 2, 3 ]
one_ds = Dataset(one_d)
one_ds.shape

(4, 1)

In [12]:
import numpy as np
m_ds = Dataset(np.random.random((3, 4, 2, 3)))
print m_ds.shape
print m_ds.nfeatures

(3, 4, 2, 3)
4


#### Load fMRI data

In [88]:
from os.path import expanduser

In [89]:
from mvpa2.datasets import *

In [90]:
home = expanduser("~")

In [91]:
tutorial_data_path=os.path.join(home, '.venv/neuropy/lib/python2.7/site-packages/mvpa2/data')

In [55]:
bold_fname = os.path.join(tutorial_data_path, 'haxby2001', 'sub001', 
                           'BOLD', 'task001_run001', 'bold_25mm.nii.gz') 

In [56]:
bold_fname

'/home/moosung/.venv/neuropy/lib/python2.7/site-packages/mvpa2/data/haxby2001/sub001/BOLD/task001_run001/bold_25mm.nii.gz'

In [57]:
ds = fmri_dataset(bold_fname)

In [58]:
len(ds)

121

In [59]:
ds.nfeatures

600

In [60]:
ds.shape

(121, 600)

In [62]:
mask_fname = os.path.join(tutorial_data_path, 'haxby2001', 'sub001',
                          'masks', '25mm', 'vt.nii.gz')
ds = fmri_dataset(bold_fname, mask=mask_fname)
len(ds)

121

In [63]:
'imghdr' in ds.a

True

## Getting data in shape

* mapper
* Load real data

### mapper

* In general, a mapper is an algorithm that transforms data. This transformation can be as simple as selecting a subset of data, or as complex as a multi-stage preprocessing pipeline. Some transformations are reversible, others are not. Some are simple one-step computations, others are iterative algorithms that have to be trained on data before they can be used. In PyMVPA, all these transformations are mappers.

Let’s create a dummy dataset (5 samples, 12 features). This time we will use a new method to create the dataset, the dataset_wizard. Here it is, fully equivalent to a regular constructor call (i.e. Dataset), but we will shortly see some nice convenience aspects.

In [65]:
from mvpa2.tutorial_suite import *
ds = dataset_wizard(np.ones((5, 12)))
ds.shape

(5, 12)

In [72]:
np.ones((5, 12))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [66]:
'mapper' in ds.a

False

Now let's look at a very similar dataset that only differs in a tiny but a very important detail:

In [68]:
ds = dataset_wizard(np.ones((5, 4, 3)))
ds.shape

(5, 12)

In [73]:
np.ones((5, 4, 3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [69]:
'mapper' in ds.a

True

In [70]:
ds.a.mapper

FlattenMapper(shape=(4, 3), auto_train=True)



We see that the resulting dataset looks identical to the one above, but this
time it got created from a 3D samples array (i.e. five samples, where each is a
4x3 matrix). Somehow this 3D array got transformed into a 2D samples array in
the dataset. This magic behavior is unveiled by observing that the dataset's
mapper is a [FlattenMapper](http://pymvpa.org/generated/mvpa2.mappers.flatten.FlattenMapper.html#mvpa2-mappers-flatten-flattenmapper).

The purpose of this mapper is precisely what we have just observed: reshaping
data arrays into 2D. It does it by preserving the first axis (in PyMVPA
datasets this is the axis that separates the samples) and concatenates all
other axis into the second one.

Since mappers represent particular transformations they can also be seen as a
protocol of what has been done. If we look at the dataset, we know that it had
been flattened on the way from its origin to a samples array in a dataset. This
feature can become really useful, if the processing become more complex. Let's
look at a possible next step -- selecting a subset of interesting features:

In [78]:
myfavs = [1, 2, 8, 10]
subds = ds[:, myfavs]
subds.shape

(5, 4)

In [79]:
subds

Dataset(array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]]), sa=SampleAttributesCollection(items=[]), fa=FeatureAttributesCollection(items=[]), a=DatasetAttributesCollection(items=[Collectable(name='mapper', doc=None, value=ChainMapper(nodes=[FlattenMapper(shape=(4, 3), auto_train=True), StaticFeatureSelection(dshape=(12,), slicearg=[1, 2, 8, 10])]))]))

In [80]:
'mapper' in subds.a

True

In [81]:
subds.a.mapper

ChainMapper(nodes=[FlattenMapper(shape=(4, 3), auto_train=True), StaticFeatureSelection(dshape=(12,), slicearg=[1, 2, 8, 10])])

### Load real data

In [92]:
data_path = os.path.join(tutorial_data_path, 'haxby2001')

In [93]:
tutorial_data_path

'/home/moosung/.venv/neuropy/lib/python2.7/site-packages/mvpa2/data'

In [94]:
data_path

'/home/moosung/.venv/neuropy/lib/python2.7/site-packages/mvpa2/data/haxby2001'

In [95]:
attr_fname = os.path.join(data_path, 'sub001',
                           'BOLD', 'task001_run001', 'bold_moest.txt')

In [96]:
attr = SampleAttributes(attr_fname)

RuntimeError: Number of entries in line [6] does not match number of columns in header [2].